version: '3.8'

services:
  jenkins:
    image: myjenkins:1
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=mydatabase
    ports:
      - "8080:8080"
    networks:
      - jenkins_net
    volumes:
      - jenkins_data:/app/data

  dockersocat:
    image: alpine/socat:latest

networks:
  jenkins_net:
    driver: overlay

volumes:
  jenkins_data:
