version: '3.8'

services:
  jenkins:
    image: myjenkins:1
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/clien
      - DOCKER_TLS_VERIFY=1
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_net
    volumes:
      - jenkins_data:/app/data
      - jenkins_certs:/certs/client:ro

  dockersocat:
    image: alpine/socat:latest

networks:
  jenkins_net:
    driver: overlay

volumes:
  jenkins_data:
  jenkins_certs:
